rvm:
  - 2.1.5
  - 2.2.0

addons:
  postgresql: "9.4"

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c "CREATE DATABASE hermes_test" -U postgres

script:
  - bundle exec rake
