# Production
#
production:
  delivery_method: :smtp

  smtp_settings:
    address:  localhost
    port:     25

  default_url_options:
    protocol: http
    host:     hermes.ifad.org


# Staging
#
staging:
  delivery_method: :smtp

  smtp_settings:
    address:  localhost
    port:     25

  default_url_options:
    protocol: http
    host:     hermes.staging.ifad.org


# Development
#
development:
  delivery_method: :smtp

  smtp_settings:
    address: localhost
    port:    25

  default_url_options:
    protocol: http
    host:     localhost
    port:     3000

# Test
#
test:
  delivery_method: :test

  default_url_options:
    protocol: http
    host:     hermes.example.org
